[platformio]
default_envs = esp32dev

[env]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 115200
build_flags =
  -Wall
  -Wextra
  -Werror

[env:esp32dev]
build_flags =
  ${env.build_flags}
  -DARMING_DELAY_MS=300000UL

[env:esp32dev-test]
build_flags =
  ${env.build_flags}
  -DARMING_DELAY_MS=10000UL
  -DENABLE_USB_COMMANDS=1
